### ISSUE TITLE
Solver Function

### ISSUE THREAD

**Issue by eriewski** [auddya/springProject2018String#16]
Given user input, solves for u(x,t)
Initializes the solution matrix

**Comment by gonuke** [comment]
This seems like an important function and deserving of a more complete description....

**Comment by auddya** [comment]
**Working algorithm**

 If u(n,i) be a general solution of any point within the domain (0,T]x (0,L)  

* Compute u( 0 , i )=I( x ( i ) ) for i=[ 0 , Nx ]
* Compute u( 1 , i ) and set u( 1 , i ) = 0 for the boundary points i=0 and i=Nx, for n=1,2,. . .,N−1,
* For each time level n=1,2,. . .,Nt−1
   * find u( n+1 , i ) for i=1,. . .,Nx−1
   * set u( n+1 , i ) = 0 for the boundary points i=0 and i=Nx.

**Function docstring**

def solver ( Initial condition, Initial string velocity, wave speed, Length of domain, Time step value, Courant number, Time, user_action=None )

   *Solve u_tt=c^2*u_xx + f on (0,L)x(0,T]

**Input**

- Initial condition, String parameters, wave speed, Time steps, C etc. 

**Output**

- Solution array gets updated after the computation

**Comment by jquincey** [comment]
@eriewski and @auddya Have completed the solver function nicely. Thanks!
