### ISSUE TITLE
Mesh Generation

### ISSUE THREAD

**Issue by eriewski** [auddya/springProject2018String#3]
Should be one of the first tasks we acomplish

**Comment by auddya** [comment]
I think one of the ways this can be done is first constructing the arrays for the solution.  
```
import numpy as np

Nx = int (round ( L / dx ) ) #Nx is the number of spatial nodes

u =  np.zeros ( Nx + 1 ) #Solution array at present time 
u_1 = np.zeros ( Nx + 1 ) #Solution array at 1 level back
u_2 = np.zeros ( Nx + 1 ) #Solution array at 2 level back 

```

**Comment by gonuke** [comment]
I suggest you focus on defining the function signature and data model, before worrying about implementation.  This will avoid writing too much code here in issue comments.  Most of your implementation code should be written in Python files and PR'ed for review.

**Comment by ajwolf4** [comment]
Something like this then?

generate_mesh( L, dx )
'''
This function will calculate the number of spatial nodes and build a solution matrix
'''

output -- solution matrix

**Comment by jquincey** [comment]
@auddya Took care of mesh generation in the solver function. Thanks!
