### ISSUE TITLE
function error_stringbreak

### ISSUE THREAD

**Issue by romarowski** [auddya/springProject2018String#5]

**Comment by romarowski** [comment]
def error_stringbreak(pluck_displacement, yield_strength):
    """This function will: - analyze the tension, force,  provoked by a particular displacement, 
                                     - convert it into stress, dividing by the string area,
                                     - compare it with the yield strength,
                                     - inform the user if the pluck breaks the string.
                                                     -> if it does, asks for new displacement.

                                    
    inputs 
    ------
    - pluck_displacement : integer
    - yield_strength   : integer

    outputs
    -------
    - result : string  
    """

**Comment by jquincey** [comment]
Future work? I don't believe that it can be addressed in time.
