### ISSUE TITLE
function get_user_input()

### ISSUE THREAD

**Issue by romarowski** [auddya/springProject2018String#6]

**Comment by romarowski** [comment]
def ask_inputs():
    This function will print in the command line a question for each input needed to
    the user and gather the information.

    
    outputs
    -------
    - data : dictionary that describes each entered feature and has its value stored.

**Comment by eriewski** [comment]
We can change later to give inputs from the user. (number of nodes, string length, etc)

**Comment by ajwolf4** [comment]
I currently have this function getting "raw input" from the user on the command line. When typing out the function handle, it will still look like "function()" and then we can pose a question and save the user's input using the raw_input() function.

**Comment by jquincey** [comment]
@ajwolf4 Dealt with this with the get_user_input function. Thanks!
