### ISSUE TITLE
Function build_matrix

### ISSUE THREAD

**Issue by eriewski** [auddya/springProject2018String#9]
def build_matrix(x_nodes, t_nodes)

This function will initialize a two dimensional matrix, where each row is an individual time step and each column is a point in space, distributed uniformly along the length of the string. This matrix will be setup to initially be empty (all zeros). The initial time step array will later be assigned to the first row. 

INPUTS
x_nodes
t_nodes

OUTPUTS
2D array of space (x) and time (t)

**Comment by ajwolf4** [comment]
I feel like this function and generate mesh are very similar. Unless, you're calculating the x_nodes in generate_mesh() and then passing it to this function. Since it's only one line of code, it could be useful just to put them together.
